config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :wines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true
  validates :wine_type, presence: true
  validates :price, presence: true
  validates :vineyard, presence: true
  validates :region, presence: true
  has_one_attached :photo
  has_one_attached :wine_region_map
  include PgSearch::Model
  pg_search_scope :search_by_name_vineyard_region_description,
    against: [ :name, :description, :region, :vineyard, :product_information, :food_pairings, :tasting_notes ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:Wines].present?
      @wines = Wine.where(wine_type: params[:Wines])

    else
      @wines = Wine.all
    end

    if params[:min].present?

      @wines = @wines.where("price > #{params[:min].to_f}")

    end

    if params[:max].present?
      @wines = @wines = @wines.where("price < #{params[:max].to_f}")
    end

    if params[:keyword].present?
      @wines = @wines.search_by_name_vineyard_region_description(params[:keyword])
    end

    @white_wines = @wines.select {|wine| wine[:wine_type].downcase == "white"}
    @red_wines = @wines.select {|wine| wine[:wine_type].downcase == "red"}
    @champagne = @wines.select {|wine| wine[:wine_type].downcase == "champagne"}
    @rose = @wines.select {|wine| wine[:wine_type].downcase == "rose"}
    @prosecco = @wines.select {|wine| wine[:wine_type].downcase == "prosecco"}
    @sparkling = @wines.select {|wine| wine[:wine_type].downcase == "sparkling"}

    wine_listings = Wine.all

    @white_list = wine_listings.select {|wine| wine[:wine_type].downcase == "white"}
    @red_list = wine_listings.select {|wine| wine[:wine_type].downcase == "red"}
    @champagne_list = wine_listings.select {|wine| wine[:wine_type].downcase == "champagne"}
    @rose_list = wine_listings.select {|wine| wine[:wine_type].downcase == "rose"}
    @prosecco_list = wine_listings.select {|wine| wine[:wine_type].downcase == "prosecco"}
    @sparkling_list = wine_listings.select {|wine| wine[:wine_type].downcase == "sparkling"}
  end

  def show
    @wine = Wine.friendly.find(params[:id])
  end

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.new(wine_params)

    if @wine.save
      qr_code = RQRCode::QRCode.new(URI.parse(request.original_url).host + "/wines/" + @wine.friendly_id)
      png = qr_code.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: 'black',
        file: nil,
        fill: 'white',
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 300
      )
      @wine.qr_code = Base64.encode64(png.to_s)
      @wine.save
      redirect_to wine_path(@wine)
    else

      render :new
    end
  end

  def destroy
    @wine = Wine.find(params[:id])
    @wine.destroy
    redirect_to wines_path
  end

  def update
    @wine = Wine.friendly.find(params[:id])
    @wine.update(wine_params)
    redirect_to wine_path(@wine)
  end

  def edit
    @wine = Wine.find(params[:id])
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :wine_type, :vineyard, :description, :organic, :biodynamic, :serving_temperature, :vintage, :agriculture_bioloique, :wine_region_map, :price, :guard, :weight, :region, :slug, :photo,  product_information: [], food_pairings: [], tasting_notes: [], allergens: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobouchonWineList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="Browse the Wine List for Le Comptoir Robouchon London.">
    <meta name="robots" content="noindex" />
    <meta property="og:type" content="website">
    <meta property="og:title" content="Le Comptoir Robouchon Wine List">
    <meta property="og:description" content="Browse the Wine List for Le Comptoir Robouchon London.">
    <meta property="og:image" content="<%= image_url('Le-Comptoir.jpg') %>">
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="twitter:title" content="Le Comptoir Wine List">
    <meta property="twitter:description" content="Browse the Wine List for Le Comptoir Robouchon London.">
    <meta property="twitter:image" content="<%= image_url('Le-Comptoir.jpg') %>">
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer card-footer">
  <p class="m-0">
    Made by Tom from <a href="https://stampapp.me">Stampapp.me</a>.
  </p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container">
    <%= link_to '/', class: "navbar-brand" do %>
      <%= image_tag "logo.jpg", style: 'height:36px;width:auto;' %>
      <% end %>

    <div id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li>
            <%= link_to "Reset Search Criteria", root_path, method: :get, class: "reset-search btn btn-outline-primary" %>
        </li>
        <li>
            <%= link_to "Search List", root_path, method: :get, class: "nav-search btn btn-primary" %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/wines/edit.html.erb
<div class="header new-form-header">
  <h3>Editing <%= @wine.name %>:</h3>
</div>
<div class="container">
  <%= simple_form_for(@wine) do |f| %>
    <div class="half-container d-flex justify-content-between">
      <div class="wine_name form-group select form-group-valid">
        <label class="select" for="name" >Name:</label>
        <input class="form-control is-valid string" type="text" placeholder="<%= @wine.name %>" id="name" readonly>
      </div>
       <%= f.input :wine_type, as: :select, collection: ["Red", "White", "Rose", "Sparkling", "Champagne", "Prosecco"], prompt: 'Select Type',label: 'Wine Type' %>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :vintage, label: 'Vintage'%>
      <%= f.input :vineyard, label: 'Vineyard' %>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :region, label: 'Region'%>
      <%= f.input :wine_region_map, as: :file %>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :serving_temperature, label: 'Serving Temperature'%>
      <%= f.input :price, as: :float, label: 'Price'%>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :guard, label: 'Guard'%>
      <%= f.input :weight, label: 'Weight'%>
    </div>
    <%= f.input :description, label: 'Wine description'%>
    <div class="multi-input-wrap" id="product-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :product_information, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='product-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <div class="multi-input-wrap" id="food-pairings-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :food_pairings, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='food-pairings-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <div class="multi-input-wrap" id="tasting-notes-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :tasting_notes, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='tasting-notes-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <div class="multi-input-wrap" id="allergens-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :allergens, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='allergens-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <%= f.input :organic %>
    <%= f.input :biodynamic %>
    <%= f.input :photo, as: :file %>
    <div class="form-submit btn btn-outline-primary">
      <%= f.button :submit, "Update" %>
    </div>
  <%end%>
</div>

app/views/wines/new.html.erb
<div class="header new-form-header">
  <h3>Add a new wine:</h3>
</div>
<div class="container">
  <%= simple_form_for(@wine) do |f| %>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :name, label: 'Wine Name' %>
      <%= f.input :wine_type, as: :select, collection: ["Red", "White", "Rose", "Sparkling", "Champagne", "Prosecco"], prompt: 'Select Type',label: 'Wine Type' %>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :vintage, label: 'Vintage'%>
      <%= f.input :vineyard, label: 'Vineyard' %>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :region, label: 'Region'%>
      <%= f.input :wine_region_map, as: :file %>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :serving_temperature, label: 'Serving Temperature'%>
      <%= f.input :price, as: :float, label: 'Price'%>
    </div>
    <div class="half-container d-flex justify-content-between">
      <%= f.input :guard, label: 'Guard'%>
      <%= f.input :weight, label: 'Weight'%>
    </div>
    <%= f.input :description, label: 'Wine description'%>
    <div class="multi-input-wrap" id="product-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :product_information, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='product-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <div class="multi-input-wrap" id="food-pairings-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :food_pairings, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='food-pairings-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <div class="multi-input-wrap" id="tasting-notes-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :tasting_notes, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='tasting-notes-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <div class="multi-input-wrap" id="allergens-info-div">
      <div class="array-inputs d-flex align-items-center">
        <%= f.input :allergens, as: :array, input_html: { class: 'form-control' } %>
        <div class='plus-btn btn btn-outline-primary' id='allergens-info-button'>
          <i class="fas fa-plus"></i>
        </div>
      </div>
    </div>
    <%= f.input :organic %>
    <%= f.input :biodynamic %>
    <%= f.input :photo, as: :file %>
    <div class="form-submit btn btn-outline-primary">
      <%= f.button :submit, "Create" %>
    </div>
  <%end%>
</div>

app/views/wines/show.html.erb
<div class="header view-header d-flex flex-column">
  <h3><%= @wine.name%></h3>
  <h5><%= @wine.vintage %></h5>
  <h5><%= @wine.vineyard%> - <%= @wine.region %> - <%= @wine.wine_type %>
  <% if user_signed_in? %>
    <div class="logged-in-links d-flex justify-content-center">
      <a href = "#" data-toggle="modal" data-target="#exampleModalCenter">
        <div class="edit-btn btn btn-outline-primary">
          Show QR code
        </div>
      </a>
      <%= link_to edit_wine_path(@wine.id) do %>
        <div class="edit-btn btn btn-outline-primary">
          edit wine
        </div>
      <% end %>
      <%= link_to wine_path(@wine.id), method: :delete, data: {confirm: "Are you sure you want to delete this wine? This action cannot be undone."} do %>
        <div class="red edit-btn btn btn-outline-primary">
          Delete
        </div>
      <% end %>
    </div>
  <% end %>
  <div id="wine-picture">
    <% if @wine.photo.attachment != nil %>
        <%= cl_image_tag @wine.photo.key, height: 150, width: 150, crop: :fill %>
    <% end %>
    <% if @wine.wine_region_map.attachment != nil %>
        <%= cl_image_tag @wine.wine_region_map.key, height: 150, width: 150, crop: :fill %>
    <% end %>
  </div>
</div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="m-head modal-header-footer modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">QR Code:</h5>
        </div>
        <div class="share-modal-body modal-body" style="text-align:center;">
          <img src="data:image/png;base64,<%= @wine.qr_code %>"/>
        </div>
        <div class="m-foot modal-header-footer modal-footer">
          <a href="data:image/png;base64,<%= @wine.qr_code %>" class="btn btn-outline-primary" download>Download</a>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       </div>
      </div>
    </div>
  </div>

<div class=container>
  <div class="description">
    <p id="price"><b>Price: £<%= number_with_precision(@wine.price, precision: 2) %> </b></p>
    <% if @wine.description? %>
    <hr>
    <p><%= @wine.description %></p>
    <% end %>
    <% if @wine.serving_temperature? %>
    <hr>
    <p>Serving Temperature: <%= @wine.serving_temperature %>.</p>
    <% end %>
    <% if @wine.guard? %>
    <hr>
    <p>Guard: <%= @wine.guard %>.</p>
    <% end %>
    <% if @wine.weight? %>
    <hr>
    <p>Weight: <%= @wine.weight %>.</p>
    <% end %>
    <% if @wine.organic? && @wine.biodynamic? %>
    <hr>
    <div class="d-flex justify-content-center image-container-logos">
      <%= image_tag "organic.jpeg" %>
      <%= image_tag "ab.jpeg" %>
      <%= image_tag "Demeter.png" %>
    </div>
    <p><%= @wine.name %> is <b>Organic</b> & <b>Biodynamic</b>.</p>
    <% elsif @wine.biodynamic? %>
    <hr>
    <div class="d-flex justify-content-center image-container-logos">
      <%= image_tag "Demeter.png" %>
    </div>
    <p><%= @wine.name %> is <b>Biodynamic</b>.<p>
    <% elsif @wine.organic? %>
    <hr>
    <div class="d-flex justify-content-center image-container-logos">
      <%= image_tag "organic.jpeg" %>
      <%= image_tag "ab.jpeg" %>
    </div>
    <p><%= @wine.name %> is <b>Organic</b>.<p>
    <% end %>
  </div>
  <% if @wine.product_information[0].length != 0 %>
    <hr class="break">
    <div class="description">
      <H5>Product Information:</H5>
      <hr>
      <% @wine.product_information.each do |i| %>
        <p><%= i %></p>
      <% end %>
    </div>
  <% end %>
  <% if @wine.tasting_notes[0].length != 0 %>
    <hr class="break">
    <div class="description">
      <H5>Tasting Notes:</H5>
      <hr>
      <% @wine.tasting_notes.each do |i| %>
        <p><%= i %></p>
      <% end %>
    </div>
  <% end %>
  <% if @wine.food_pairings[0].length != 0 %>
    <hr class="break">
    <div class="description">
      <H5>Food Pairings:</H5>
      <hr>
      <% @wine.food_pairings.each do |i| %>
        <p><%= i %></p>
      <% end %>
    </div>
  <% end %>
  <% if @wine.allergens[0].length != 0 %>
    <hr class="break">
    <div class="description">
      <H5>Allergens:</H5>
      <hr>
      <% @wine.allergens.each do |i| %>
        <p><%= i %></p>
      <% end %>
    </div>
  <% else %>
    <hr class="break">
    <div class="description">
      <H5>Allergens:</H5>
      <hr>
      <p>This product does not contain any known allergens.</p>
  <% end %>
</div>
</div>